### ISSUE TITLE
Failed to find video player inside frame

### ISSUE THREAD

**Issue by AndrewJacop** [NobilityDeviant/Wcofun.com_Downloader#3]
[21:01] Failed to find video player inside frame for https://www.wcofun.net/cardfight-vanguard-episode-1-english-dubbed. Retrying...

**Comment by NobilityDeviant** [comment]
It seems like lag. Just retry it a couple times. I downloaded that video just fine a few moments ago. What browser are you using?

**Comment by AndrewJacop** [comment]
I tried Chrome and Firefox
Still not working and nothing added in the Downloads

**Comment by NobilityDeviant** [comment]
Try updating your browsers to the latest version. I will release a new version to help debug better.

NOTE TO EVERYONE: 

I know there is some issues for certain people, but it doesn't happen for everyone so it's gets pretty technical.
This project may look small, but it's very complicated due to the compatibility issues.
Different operating systems, different browsers, different permissions, different internet providers (speed, black listing etc)
You will have to give me time to sort it all out. 
I have been developing this program with no one using it for awhile and now there's people for some reason, so give it time.
Sorry but this is a side project and wont be my top priority. That doesn't mean i'm not trying though.

**Comment by NobilityDeviant** [comment]
If this keeps happening then open another issue.
