### ISSUE TITLE
Browser's Binary?

### ISSUE THREAD

**Issue by CodeJBDA** [NobilityDeviant/Wcofun.com_Downloader#8]
Hi There,

Thank you so much for this! I have been struggling with single episode downloading for a WHILE.
I am getting this error
![image](https://user-images.githubusercontent.com/42821787/232222886-9f2880cf-7daf-4bca-96de-da73c0a927ac.png)

I am using the latest version of FireFox, I do NOT have Chrome installed on my PC.

**Comment by KreeperSteve** [comment]
![Error 4_30_2023 8_51_45 PM](https://user-images.githubusercontent.com/40222220/235389785-e1a4bcb2-cc9a-4f50-a158-e56332d7fdd0.png)

**Comment by Mr-Halpin001** [comment]
Hey bro! you are doing a great deed for us all anime lovers here, if you want I can help you in your quest. I am tiny dev too, I would be happy to land a hand.

**Comment by NobilityDeviant** [comment]
> Hi There,
> 
> Thank you so much for this! I have been struggling with single episode downloading for a WHILE. I am getting this error ![image](https://user-images.githubusercontent.com/42821787/232222886-9f2880cf-7daf-4bca-96de-da73c0a927ac.png)
> 
> I am using the latest version of FireFox, I do NOT have Chrome installed on my PC.

You have to pick firefox in the settings. 
CTRL + S  and
![Example](https://i.ibb.co/5THV5SG/Screenshot-1.png)

**Comment by NobilityDeviant** [comment]
the selenium issue will be fixed in the next update.
i believe it is an issue with the latest browser updates



> Hey bro! you are doing a great deed for us all anime lovers here, if you want I can help you in your quest. I am tiny dev too, I would be happy to land a hand.

I would love some help. I am not entirely sure how but if you know how to work github, try sending some pull requests with whatever changes or improvements you can think of. This can either be java or kotlin and even some layout changes if you know how to edit fxml files.

Do note that i have been learning compose and the javafx branch will become obsolete eventually.

**Comment by NobilityDeviant** [comment]
This issue has been resolved https://github.com/NobilityDeviant/Wcofun.com_Downloader/commit/314d216f3b867102285f9412e1e04db96e19f6a5
